import {mkdir, writeFile, copyFile, cp} from 'node:fs/promises';
import {projects, github} from '../content.mjs';
const out = new URL('../dist/', import.meta.url);
await mkdir(out, {recursive: true});
await mkdir(new URL('projects/',out), {recursive:true});
await cp(new URL('../public/',import.meta.url), out, {recursive:true});
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const bi=(en,zh)=>`<span lang="en">${esc(en)}</span><span lang="zh-CN">${esc(zh)}</span>`;
const pair=a=>bi(...a);
const base='https://2273862959-sketch.github.io';
const header=(prefix='')=>`<header><div class="nav-wrap"><a class="wordmark" href="${prefix}index.html" aria-label="MA JIYU home">MJ<span class="brand-square">.</span></a><nav aria-label="Main navigation"><a href="${prefix}index.html#about">${bi('About','关于')}</a><a href="${prefix}index.html#projects">${bi('Projects','项目')}</a><a href="${prefix}index.html#practice">${bi('Toolkit','技术')}</a><a href="${github}">GitHub <span aria-hidden="true">↗</span></a></nav><button class="language" type="button" aria-label="Switch language to Chinese" aria-pressed="false">EN <span>/</span> 中文</button></div></header>`;
const footer=(prefix='')=>`<footer><a class="footer-name" href="${prefix}index.html">MA JIYU<span>马济宇</span></a><p>${bi('Learning through building. Documenting along the way.','在实践中学习，在记录中进步。')}</p><a href="${github}">GitHub ↗</a><small>© 2026 MA JIYU</small></footer>`;
const head=(title,description,prefix='',canonical='')=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | MA JIYU</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${base}/${canonical}"><meta name="theme-color" content="#f7f8fa"><link rel="icon" href="${prefix}favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="${prefix}style.css"><script src="${prefix}app.js" defer></script></head><body><a class="skip-link" href="#main">Skip to content</a>${header(prefix)}`;
const visual=(p,prefix='')=>p.image?`<img src="${prefix}assets/${p.image}" alt="${esc(p.name)} project visual" width="1200" height="750" loading="lazy">`:`<div class="type-cover ${p.id==='particle-bouquet'?'rose-cover':'ml-cover'}"><span>${p.id==='particle-bouquet'?'CREATIVE CODING':'LEARNING NOTES'}</span><strong>${p.id==='particle-bouquet'?'A thousand points.':'From data,\nto understanding.'}</strong><span>${p.id==='particle-bouquet'?'ONE BOUQUET · 360°':'NUMPY → KERAS → CNN'}</span></div>`;
const card=(p,i)=>`<article class="project-card"><a class="project-visual" href="projects/${p.id}.html" aria-label="${esc(p.name)} case study">${visual(p)}</a><div class="card-body"><div class="card-eyebrow"><span>${pair(p.category)}</span><span class="project-number">${String(i+1).padStart(2,'0')}</span></div><h3><a href="projects/${p.id}.html">${bi(p.name,p.zhName)}</a></h3><p>${pair(p.description)}</p><ul class="tags" aria-label="Technologies">${p.tags.map(t=>`<li>${esc(t)}</li>`).join('')}</ul><div class="card-bottom"><span>${pair(p.status)}</span><a href="projects/${p.id}.html">${bi('View project','查看项目')} <span aria-hidden="true">↗</span></a></div></div></article>`;
const home=`${head('Portfolio','Projects in machine learning, web engineering, interactive systems and scientific computing by MA JIYU.')}
<main id="main"><section class="hero wrap" id="about"><div class="hero-main"><p class="eyebrow">${bi('A PERSONAL RECORD OF THINGS BUILT','个人项目与实践记录')}</p><h1>MA JIYU<span class="chinese-name">马济宇</span></h1><p class="hero-role">${bi('Learning from data.','从数据中学习。')}<br><em>${bi('Building for people.','为真实使用而构建。')}</em></p><p class="hero-description">${bi('I explore machine learning, scientific computing and interactive software. My projects connect experiments with working applications—from facial expression recognition to product websites and games.','我关注机器学习、科学计算与交互软件。通过表情识别、产品网站和游戏等项目，将实验过程连接到实际可用的应用。')}</p><div class="hero-actions"><a class="button primary" href="#projects">${bi('Explore my work','浏览我的项目')} <span aria-hidden="true">↓</span></a><a class="text-link" href="${github}">${bi('Find me on GitHub','我的 GitHub')} ↗</a></div></div><aside class="hero-index" aria-label="Selected project index"><div class="index-header">${bi('IN FOCUS','重点项目')}<span>2026</span></div>${projects.slice(0,4).map((p,i)=>`<a href="projects/${p.id}.html"><span class="index-num">0${i+1}</span><div><strong>${bi(p.name,p.zhName)}</strong><span>${pair(p.category)}</span></div><span aria-hidden="true">↗</span></a>`).join('')}<div class="index-foot">${bi('Code, case studies & documented experiments','源码、案例与实验记录')}</div></aside></section>
<div class="intro-strip"><div class="wrap"><span>${bi('AREAS OF PRACTICE','实践方向')}</span><p>Machine Learning <b> / </b> Web Engineering <b> / </b> Creative Coding</p></div></div>
<section class="wrap work-section" id="projects"><div class="section-heading"><div><p class="eyebrow">${bi('PROJECT COLLECTION','项目集合')}</p><h2>${bi('Ideas, made tangible.','让想法成为作品。')}</h2></div><p>${bi('Eight projects and studies. Each with its own question, process and outcome.','八个项目与实践，各自记录问题、过程与成果。')}</p></div><div class="project-grid">${projects.map(card).join('')}</div></section>
<section class="practice-section" id="practice"><div class="wrap practice-layout"><div><p class="eyebrow">${bi('TOOLKIT & APPROACH','技术与方法')}</p><h2>${bi('Across disciplines.','跨越不同领域，')}<br><em>${bi('Grounded in practice.','落在具体实践。')}</em></h2><p>${bi('The tools change with the problem. The habit stays the same: build, examine, document and improve.','工具随着问题变化，习惯保持一致：构建、检验、记录、改进。')}</p></div><div class="tool-groups"><div><h3>${bi('Learning & perception','学习与感知')}</h3><p>Python · PyTorch · TensorFlow / Keras · OpenCV</p></div><div><h3>${bi('Applications & interfaces','应用与界面')}</h3><p>TypeScript · React · FastAPI · C++ · EasyX</p></div><div><h3>${bi('Data & communication','数据与表达')}</h3><p>Pandas · NumPy · Matplotlib · Cartopy · SEO / GEO</p></div></div></div></section></main>${footer()} </body></html>`;
await writeFile(new URL('index.html',out),home);
for(const p of projects){
  const links=p.links.map(([en,zh,url])=>`<a class="button ${url.includes('github.com')?'secondary':'primary'}" href="${esc(url)}">${bi(en,zh)} ↗</a>`).join('');
  const html=`${head(p.name,p.description[0],'../',`projects/${p.id}.html`)}<main id="main" class="wrap detail"><a class="back-link" href="../index.html#projects">← ${bi('All projects','全部项目')}</a><div class="detail-title"><div><p class="eyebrow">${pair(p.category)}</p><h1>${bi(p.name,p.zhName)}</h1><p class="detail-subtitle">${pair(p.subtitle)}</p></div><div class="metric"><strong>${p.metric[0]}</strong><span>${bi(p.metric[1],p.metric[2])}</span></div></div><div class="detail-links">${links}<span class="detail-status">${pair(p.status)}</span></div><figure class="detail-visual">${visual(p,'../')}</figure><div class="detail-body"><aside><p class="eyebrow">${bi('BUILT WITH','技术栈')}</p><ul class="tags">${p.tags.map(t=>`<li>${t}</li>`).join('')}</ul><p class="eyebrow">${bi('PROJECT NOTES','项目说明')}</p><p>${pair(p.scope)}</p></aside><div class="case-content"><section><p class="eyebrow">01 / ${bi('THE QUESTION','问题')}</p><h2>${bi('What needed to work?','需要解决什么？')}</h2><p>${pair(p.problem)}</p></section><section><p class="eyebrow">02 / ${bi('THE PROCESS','方法')}</p><h2>${bi('How it comes together.','如何将它实现。')}</h2><ol>${p.method.map(m=>`<li>${pair(m)}</li>`).join('')}</ol></section><section><p class="eyebrow">03 / ${bi('THE OUTCOME','成果')}</p><h2>${bi('What the work shows.','项目所呈现的结果。')}</h2><p>${pair(p.outcome)}</p>${(p.figures||[]).map(([img,en,zh])=>`<figure class="evidence"><img src="../assets/${img}" alt="${esc(en)}" loading="lazy"><figcaption>${bi(en,zh)}</figcaption></figure>`).join('')}</section></div></div><div class="more-projects"><h2>${bi('Keep exploring.','继续浏览。')}</h2>${projects.filter(x=>x.id!==p.id).slice(0,3).map(x=>`<a href="${x.id}.html">${bi(x.name,x.zhName)} ↗</a>`).join('')}</div></main>${footer('../')}</body></html>`;
  await writeFile(new URL(`projects/${p.id}.html`,out),html);
}
await writeFile(new URL('404.html',out),`${head('Page not found','Return to the project collection.','/','404.html')}<main id="main" class="wrap detail"><h1>404</h1><p>${bi('This page is not here.','这个页面不存在。')}</p><a class="button primary" href="/">${bi('Back to home','返回首页')}</a></main>${footer('/')}</body></html>`);
await writeFile(new URL('.nojekyll',out),'');
await writeFile(new URL('robots.txt',out),`User-agent: *\nAllow: /\nSitemap: ${base}/sitemap.xml\n`);
await writeFile(new URL('sitemap.xml',out),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>${base}/</loc></url>${projects.map(p=>`<url><loc>${base}/projects/${p.id}.html</loc></url>`).join('')}</urlset>`);
console.log(`Built homepage, ${projects.length} project pages, 404 and sitemap.`);
