import {mkdir, writeFile, cp} from 'node:fs/promises';
import {projects, github} from '../content.mjs';

const out = new URL('../dist/', import.meta.url);
const base = 'https://2273862959-sketch.github.io';
await mkdir(new URL('projects/', out), {recursive: true});
await cp(new URL('../public/', import.meta.url), out, {recursive: true});
const esc = value => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
const bi = (en, zh) => `<span lang="en">${esc(en)}</span><span lang="zh-CN">${esc(zh)}</span>`;
const pair = value => bi(...value);
const arrow = '<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M5 19 19 5M5 5h14v14" stroke="currentColor" stroke-width="1.5"/></svg>';
const star = '<svg class="asterisk" viewBox="0 0 80 80" fill="none" aria-hidden="true"><path d="M40 0v80M0 40h80M12 12l56 56M12 68l56-56" stroke="currentColor" stroke-width="9"/></svg>';
const header = (prefix = '') => `<header class="site-header"><div class="nav-wrap"><a class="wordmark" href="${prefix}index.html" aria-label="MA JIYU home"><span class="monogram">m<span>j</span>.</span><span class="wordmark-name">MA JIYU<span>PORTFOLIO / 2026</span></span></a><nav aria-label="Main navigation"><a href="${prefix}index.html#about">${bi('About', '关于')}</a><a href="${prefix}index.html#projects">${bi('Work', '作品')}</a><a href="${prefix}index.html#practice">${bi('Approach', '方法')}</a></nav><div class="nav-actions"><button class="language" type="button" aria-label="Switch language to Chinese" aria-pressed="false">EN <span>/</span> 中</button><a class="github-nav" href="${github}">GitHub ${arrow}</a></div></div></header>`;
const footer = (prefix = '') => `<footer><div class="wrap"><div class="footer-main"><div><p class="eyebrow">${bi('THE NEXT CHAPTER', '下一段探索')}</p><h2>${bi('Always learning.', '持续学习，')}<br><em>${bi('Always building.', '不断创造。')}</em></h2></div><a class="footer-github" href="${github}">${bi('Follow the work', '关注我的作品')}${arrow}</a></div><div class="footer-bottom"><a href="${prefix}index.html">MA JIYU <span>马济宇</span></a><p>${bi('Made with curiosity. Built with care.', '好奇心驱动，认真地构建。')}</p><span>© 2026</span><a href="#top">${bi('Back to top ↑', '返回顶部 ↑')}</a></div></div></footer>`;
const head = (title, description, prefix = '', canonical = '') => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | MA JIYU</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${base}/${canonical}"><meta name="theme-color" content="#f7f6f2"><meta property="og:title" content="${esc(title)} | MA JIYU"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><meta property="og:url" content="${base}/${canonical}"><link rel="icon" href="${prefix}favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="${prefix}style.css?v=2"><script src="${prefix}app.js?v=2" defer></script></head><body id="top"><a class="skip-link" href="#main">Skip to content</a>${header(prefix)}`;
const visual = (p, prefix = '') => p.image
  ? `<img src="${prefix}assets/${p.image}" alt="${esc(p.name)} — project visual" width="1200" height="750" loading="lazy" decoding="async">`
  : `<div class="type-cover ${p.id === 'particle-bouquet' ? 'rose-cover' : 'ml-cover'}"><span>${p.id === 'particle-bouquet' ? 'PARTICLES / MOTION / INTERACTION' : 'LEARNING NOTES / 01—04'}</span><div class="cover-symbol" aria-hidden="true">${p.id === 'particle-bouquet' ? '✳' : 'ƒ(x)'}</div><strong>${p.id === 'particle-bouquet' ? 'A thousand points.\nOne bouquet.' : 'From data,\nto understanding.'}</strong></div>`;
const tags = p => `<ul class="tags" aria-label="Technologies">${p.tags.map(t => `<li>${esc(t)}</li>`).join('')}</ul>`;
const featured = (p, i) => `<article class="feature feature-${p.id}"><a class="feature-visual" href="projects/${p.id}.html" aria-label="${esc(p.name)} case study"><div class="visual-topline"><span>${esc(p.name.toUpperCase())} / PREVIEW</span><span class="window-dots" aria-hidden="true">● ● ●</span></div><div class="feature-screen">${visual(p)}</div><span class="visual-open">${arrow}</span></a><div class="feature-info"><div class="project-kicker"><span>0${i + 1} / ${pair(p.category)}</span><span class="project-state"><i></i>${pair(p.status)}</span></div><h3><a href="projects/${p.id}.html">${bi(p.name, p.zhName)}</a></h3><p class="feature-subtitle">${pair(p.subtitle)}</p><p>${pair(p.description)}</p>${tags(p)}<div class="feature-bottom"><div class="mini-metric"><strong>${p.metric[0]}</strong><span>${bi(p.metric[1], p.metric[2])}</span></div><a class="round-link" href="projects/${p.id}.html" aria-label="${esc(p.name)} case study">${arrow}</a></div></div></article>`;
const card = (p, i) => `<article class="project-card" data-category="${['plants-vs-zombies','garden-guardian','particle-bouquet'].includes(p.id) ? 'interactive' : 'learning'}"><a class="project-visual" href="projects/${p.id}.html" aria-label="${esc(p.name)} case study">${visual(p)}<span class="visual-open">${arrow}</span></a><div class="card-body"><div class="project-kicker"><span>${pair(p.category)}</span><span>0${i + 3}</span></div><h3><a href="projects/${p.id}.html">${bi(p.name, p.zhName)}</a></h3><p>${pair(p.description)}</p>${tags(p)}<div class="card-bottom"><span>${pair(p.status)}</span><a href="projects/${p.id}.html">${bi('Explore project', '了解项目')}${arrow}</a></div></div></article>`;

const home = `${head('Portfolio', 'MA JIYU — a personal collection of machine learning, web engineering, games and scientific computing.')}
<main id="main">
<section class="hero wrap" id="about"><div class="hero-copy"><p class="eyebrow hero-eyebrow"><span class="live-dot"></span>${bi('CURIOUS MIND. HANDS-ON BUILDER.', '保持好奇，动手创造。')}</p><h1>MA JIYU<span class="name-note">马济宇 / PORTFOLIO</span></h1><h2 class="hero-statement">${bi('Turning curiosity', '把好奇心，')}<br>${bi('into ', '变成')}<em>${bi('things that work.', '真实的作品。')}</em></h2><p class="hero-description">${bi('At the intersection of machine learning, thoughtful interfaces and creative code. I learn by building—and make the process part of the story.', '在机器学习、交互设计与创意编程之间探索。通过构建真实项目学习，也认真记录每一次实验、实现与改进。')}</p><div class="hero-actions"><a class="button primary" href="#projects">${bi('Explore selected work', '浏览精选作品')}<span>↘</span></a><a class="text-link" href="${github}">${bi('My GitHub', '我的 GitHub')}${arrow}</a></div><div class="hero-footnote"><span>01 — 08</span><p>${bi('Eight projects. Different questions.\nOne habit: keep making.', '八个项目，不同的问题。\n同一个习惯：持续创造。')}</p></div></div><div class="portrait-composition"><div class="portrait-orbit" aria-hidden="true"></div><div class="portrait-topline"><span>THE PERSON BEHIND THE PROJECTS</span><span>01 / MJ</span></div><figure class="portrait-frame"><img class="portrait" src="assets/portrait.jpg" alt="Portrait of MA JIYU" width="688" height="982" fetchpriority="high"><figcaption><span>MA JIYU</span><span>马济宇</span></figcaption></figure><div class="portrait-sticker">${star}<span>${bi('IDEAS INTO\nREALITY', '从想法\n到实现')}</span></div><div class="portrait-caption"><span class="caption-line"></span>${bi('A personal collection of experiments & applications.', '个人实验与应用作品集。')}</div></div></section>
<div class="discipline-strip"><div class="wrap"><span>${bi('MY PLAYGROUND', '探索的领域')}</span><p>Machine Learning <i>✳</i> Web Engineering <i>✳</i> Creative Coding</p></div></div>
<section class="selected-section wrap" id="projects"><div class="section-heading"><div><p class="eyebrow">01 / ${bi('SELECTED WORK', '精选作品')}</p><h2>${bi('Built with purpose.', '让想法，')}<br><em>${bi('Made to be explored.', '值得被看见。')}</em></h2></div><p>${bi('A closer look at the systems I build: the questions, the decisions, and the evidence behind them.', '走进项目背后的问题、设计选择与实现过程，看看想法如何变成可以使用的系统。')}</p></div><div class="featured-projects">${projects.slice(0,2).map(featured).join('')}</div></section>
<section class="collection-section wrap" id="collection"><div class="collection-heading"><div><p class="eyebrow">02 / ${bi('MORE TO EXPLORE', '更多探索')}</p><h2>${bi('The rest of the collection.', '不止一种可能。')}</h2></div><div class="filters" role="group" aria-label="Filter projects"><button type="button" data-filter="all" aria-pressed="true">${bi('All work', '全部')}</button><button type="button" data-filter="interactive" aria-pressed="false">${bi('Games & creative', '游戏与创意')}</button><button type="button" data-filter="learning" aria-pressed="false">${bi('AI & data', 'AI 与数据')}</button></div></div><p class="filter-count sr-only" aria-live="polite"></p><div class="project-grid">${projects.slice(2).map(card).join('')}</div></section>
<section class="practice-section" id="practice"><div class="wrap"><div class="practice-intro"><div><p class="eyebrow">03 / ${bi('HOW I WORK', '我的方法')}</p><h2>${bi('Different tools.', '工具在变，')}<br><em>${bi('The same curiosity.', '好奇心不变。')}</em></h2></div><p>${bi('A project is more than its final screen. I care about understanding the problem, testing the choices and making the work understandable to someone else.', '项目不只是一张最终效果图。我关注问题本身，检验实现中的选择，也让别人能看懂过程与结果。')}</p></div><div class="practice-grid"><article><span class="practice-number">01 /</span><h3>${bi('Learn & experiment', '学习与实验')}</h3><p>${bi('Explore data, train models and examine where predictions fail.', '探索数据、训练模型，也关注预测为什么会失败。')}</p><div>Python · PyTorch · TensorFlow<br>OpenCV · NumPy</div></article><article><span class="practice-number">02 /</span><h3>${bi('Build & interact', '构建与交互')}</h3><p>${bi('Connect the underlying logic to interfaces people can actually use.', '把底层逻辑连接到真正可以操作和使用的界面。')}</p><div>TypeScript · React · FastAPI<br>C++ · EasyX</div></article><article><span class="practice-number">03 /</span><h3>${bi('Examine & explain', '检验与表达')}</h3><p>${bi('Document the methods, visualize the evidence and acknowledge the limits.', '记录方法、可视化证据，也如实说明项目的边界。')}</p><div>Pandas · Matplotlib · Cartopy<br>Scientific Computing · SEO / GEO</div></article></div></div></section>
</main>${footer()}</body></html>`;
await writeFile(new URL('index.html',out),home);

for (const [index,p] of projects.entries()) {
 const links = p.links.map(([en,zh,url]) => `<a class="button ${url.includes('github.com')?'secondary':'primary'}" href="${esc(url)}">${bi(en,zh)}${arrow}</a>`).join('');
 const html = `${head(p.name,p.description[0],'../',`projects/${p.id}.html`)}<main id="main" class="wrap detail"><div class="detail-breadcrumb"><a href="../index.html#projects">← ${bi('Back to work', '返回作品集')}</a><span>PROJECT / ${String(index+1).padStart(2,'0')}</span></div><div class="detail-title"><div><p class="eyebrow">${pair(p.category)}</p><h1>${bi(p.name,p.zhName)}</h1><p class="detail-subtitle">${pair(p.subtitle)}</p></div><div class="metric"><strong>${p.metric[0]}</strong><span>${bi(p.metric[1],p.metric[2])}</span></div></div><div class="detail-links">${links}<span class="detail-status"><i></i>${pair(p.status)}</span></div><figure class="detail-visual visual-${p.id}">${visual(p,'../')}</figure><div class="detail-body"><aside><p class="eyebrow">${bi('THE TOOLKIT', '技术栈')}</p>${tags(p)}<p class="eyebrow">${bi('CONTEXT & BOUNDARIES', '背景与边界')}</p><p>${pair(p.scope)}</p></aside><div class="case-content"><section><span class="case-number">01</span><div><p class="eyebrow">${bi('THE QUESTION', '问题')}</p><h2>${bi('What needed to work?', '需要解决什么？')}</h2><p>${pair(p.problem)}</p></div></section><section><span class="case-number">02</span><div><p class="eyebrow">${bi('THE PROCESS', '方法')}</p><h2>${bi('How it comes together.', '如何将它实现。')}</h2><ol>${p.method.map(m=>`<li>${pair(m)}</li>`).join('')}</ol></div></section><section><span class="case-number">03</span><div><p class="eyebrow">${bi('THE OUTCOME', '成果')}</p><h2>${bi('What the work shows.', '项目所呈现的结果。')}</h2><p>${pair(p.outcome)}</p>${(p.figures||[]).map(([img,en,zh])=>`<figure class="evidence"><img src="../assets/${img}" alt="${esc(en)}" loading="lazy"><figcaption>${bi(en,zh)}</figcaption></figure>`).join('')}</div></section></div></div><div class="more-projects"><h2>${bi('Another direction.', '另一个方向。')}</h2>${projects.filter(x=>x.id!==p.id).slice(0,3).map(x=>`<a href="${x.id}.html">${bi(x.name,x.zhName)}${arrow}</a>`).join('')}</div></main>${footer('../')}</body></html>`;
 await writeFile(new URL(`projects/${p.id}.html`, out), html);
}
await writeFile(new URL('404.html',out),`${head('Page not found','Return to the project collection.','/','404.html')}<main id="main" class="wrap detail"><h1>404</h1><p>${bi('A little off the path. Let’s get you back.', '暂时偏离了路线，让我们回到作品集。')}</p><a class="button primary" href="/">${bi('Back to home','返回首页')}${arrow}</a></main>${footer('/')}</body></html>`);
await writeFile(new URL('.nojekyll',out),'');
await writeFile(new URL('robots.txt',out),`User-agent: *\nAllow: /\nSitemap: ${base}/sitemap.xml\n`);
await writeFile(new URL('sitemap.xml',out),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>${base}/</loc></url>${projects.map(p=>`<url><loc>${base}/projects/${p.id}.html</loc></url>`).join('')}</urlset>`);
console.log(`Built redesigned portfolio, ${projects.length} case studies, 404 and sitemap.`);
